// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0iiV9s7hwLVyI6lAp4nQ-woZiNxyYXgo',
    appId: '1:796622223332:web:27773f85fc0834922bb9f1',
    messagingSenderId: '796622223332',
    projectId: 'flutter-kova-chat',
    authDomain: 'flutter-kova-chat.firebaseapp.com',
    storageBucket: 'flutter-kova-chat.firebasestorage.app',
    measurementId: 'G-E7ZGKN348W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUUoSEMRlG4wObStgqH9mobjD1b_HQErk',
    appId: '1:796622223332:android:26ebf99bb373fa2c2bb9f1',
    messagingSenderId: '796622223332',
    projectId: 'flutter-kova-chat',
    storageBucket: 'flutter-kova-chat.firebasestorage.app',
  );
}
